# @package logger
_target_: biosignals.loggers.wandb.WandbLogger

project: biosignals
name: ${hydra:job.name}-${now:%Y%m%d_%H%M%S}
dir: ${hydra:runtime.output_dir}

entity: null
group: null
job_type: train
tags: []

mode: online   # set to offline if needed
