# @package dataset

train:
  _target_: biosignals.data.datasets.ecg_npz.EcgNpZDataset
  root: ${oc.env:DATA_DIR,./data}/ptbxl_npz
  split: train

val:
  _target_: biosignals.data.datasets.ecg_npz.EcgNpZDataset
  root: ${oc.env:DATA_DIR,./data}/ptbxl_npz
  split: val

cache:
  train: null
  val: ${oc.env:CACHE_DIR,./cache}/ptbxl/val
