# @package dataset

train:
  _target_: biosignals.data.datasets.windowed_npz.WindowedNpzDataset
  root: ${oc.env:DATA_DIR,./data}/standardized/mitbih/v1
  split: train
  view: views/windows.parquet
  subjects_dir: subjects
  modalities: ["main"]
  label_col: label_id
  dropna_labels: true
  subject_cache_size: 2   # records are large; keep cache small per worker

  subject_col: subject_id   # grouping/person id
  npz_col: record_id        # file id
  id_col: example_id        # unique window id

val:
  _target_: biosignals.data.datasets.windowed_npz.WindowedNpzDataset
  root: ${oc.env:DATA_DIR,./data}/standardized/mitbih/v1
  split: val
  view: views/windows.parquet
  subjects_dir: subjects
  modalities: ["main"]
  label_col: label_id
  dropna_labels: true
  subject_cache_size: 2

  subject_col: subject_id
  npz_col: record_id
  id_col: example_id

test:
  _target_: biosignals.data.datasets.windowed_npz.WindowedNpzDataset
  root: ${oc.env:DATA_DIR,./data}/standardized/mitbih/v1
  split: test
  view: views/windows.parquet
  subjects_dir: subjects
  modalities: ["main"]
  label_col: label_id
  dropna_labels: true
  subject_cache_size: 2

  subject_col: subject_id
  npz_col: record_id
  id_col: example_id


# Wrapper-only settings live HERE (not inside train/val/test nodes)
cache:
  train: null
  val: null
  test: null
