# @package transforms

params:
  default_fs: 360.0
  notch_hz: 60.0

# Beat windows are already fixed-length - no crop transforms needed

train:
  _target_: biosignals.data.transforms.compose.Compose
  transforms:
    - _target_: biosignals.data.transforms.signal_ops.EnsureFloat32
    - _target_: biosignals.data.transforms.signal_ops.BandpassButter
      low_hz: 0.5
      high_hz: 40.0
      order: 4
      default_fs: ${transforms.params.default_fs}
    - _target_: biosignals.data.transforms.signal_ops.NotchFilter
      freq_hz: ${transforms.params.notch_hz}
      q: 30.0
      default_fs: ${transforms.params.default_fs}
    - _target_: biosignals.data.transforms.signal_ops.ZScorePerChannel

val:
  _target_: biosignals.data.transforms.compose.Compose
  transforms:
    - _target_: biosignals.data.transforms.signal_ops.EnsureFloat32
    - _target_: biosignals.data.transforms.signal_ops.BandpassButter
      low_hz: 0.5
      high_hz: 40.0
      order: 4
      default_fs: ${transforms.params.default_fs}
    - _target_: biosignals.data.transforms.signal_ops.NotchFilter
      freq_hz: ${transforms.params.notch_hz}
      q: 30.0
      default_fs: ${transforms.params.default_fs}
    - _target_: biosignals.data.transforms.signal_ops.ZScorePerChannel

test:
  _target_: biosignals.data.transforms.compose.Compose
  transforms:
    - _target_: biosignals.data.transforms.signal_ops.EnsureFloat32
    - _target_: biosignals.data.transforms.signal_ops.BandpassButter
      low_hz: 0.5
      high_hz: 40.0
      order: 4
      default_fs: ${transforms.params.default_fs}
    - _target_: biosignals.data.transforms.signal_ops.NotchFilter
      freq_hz: ${transforms.params.notch_hz}
      q: 30.0
      default_fs: ${transforms.params.default_fs}
    - _target_: biosignals.data.transforms.signal_ops.ZScorePerChannel
